export const SUBSCRIPTION_TYPE = {
  MONTHLY: 'monthly',
  YEARLY: 'yearly',
  FREE: 'free',
  SYSTEM: 'system'
};

export const SUBSCRIPTION_STATUS = {
  ACTIVE: 'active',
  DEACTIVATED: 'deactivated'
};

export const UPDATE_PERFORMER_SUBSCRIPTION_CHANNEL = 'UPDATE_PERFORMER_SUBSCRIPTION_CHANNEL';
export const CANCEL_PERFORMER_SUBSCRIPTION_CHANNEL = 'CANCEL_PERFORMER_SUBSCRIPTION_CHANNEL';
